config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :passengers
  root 'welcome#index'
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  validates :name, presence: true,
                   length: { minimum: 2 }

end

app/models/train.rb
class Train < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

  # new passenger form
  def new
    @passenger = Passenger.new
  end

  # update a passenger
  def edit
    @passenger = Passenger.find(params[:id])
  end

  # add a new passenger
  def create
    @passenger = Passenger.new(passenger_params)
    if @passenger.save
      redirect_to @passenger
    else
      render 'new'
    end
  end

  def update
    @passenger = Passenger.find(params[:id])

    if @passenger.update(passenger_params)
      redirect_to @passenger
    else
      render 'edit'
    end
  end

  # passenger manifest
  def index
    @passengers = Passenger.all
  end

  # show a passenger
  def show
    @passenger = Passenger.find(params[:id])
    puts @passenger.name
  end

  # remove a passenger; Good bye!
  def destroy
    @passenger = Passenger.find(params[:id])
    @passenger.destroy

    redirect_to passengers_path
  end

  private
  def passenger_params
    params.require(:passenger).permit(:name, :saying)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffeeExpress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/passengers/_form.html.erb
<%= form_for @passenger do |f| %>

<% if @passenger.errors.any? %>
<div id"'error">
  <h2>
    <%= pluralize(@passenger.errors.count, "error") %>
    prevented this passenger from on boarding:
  </h2>
  <ul>
    <% @passenger.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<dl>
  <dt><%= f.label :name %></dt>
  <dd><%= f.text_field :name %></dd>

  <dt><%= f.label :saying %></dt>
  <dd><%= f.text_field :saying %></dd>
</dl>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/passengers/edit.html.erb
<h1><%= @passenger.name %></h1>

<p>
  So you want to update the <%= @passenger.name %>?
</p>

<%= render 'form' %>

<div>
  <a href="/passengers">See All Passengers</a>
</div>

<div>
<a href="/" title="home">↩ Back to the station</a>
</div>

app/views/passengers/index.html.erb
<h1>All the passengers</h1>

<p>
  Here are all the riders of our Coffee Express train.
  We would like to thank the Conductors, the Engineers,
  and of course our Passengers, without which the
  Coffee Express train wouldn't be possible.
  Thank you.
</p>

<section>
  <h1>Passenger Manifest</h1>

  <p>
    Here are the riders of the Coffee Express!
  </p>

  <table>
    <tr>
      <th>Name</th>
      <th>Saying</th>
      <th>Remove</th>
    </tr>

    <% @passengers.each do |passenger| %>
    <tr>
      <td class="name"><a href="/passengers/<%= passenger.id %>"><%= passenger.name %></a></td>
      <td class="saying"><%= passenger.saying %></td>
      <td>
        <%= link_to '⌫', passenger_path(passenger),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>

</section>

<section>
  <h1>New passenger?</h1>

  <p>
    New passengers are always welcome!
  </p>

  <p><%= link_to 'Sign up for Coffee Express!', new_passenger_path %></p>
</section>

<a href="/" title="home">↩ Back to the station</a>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<p>
  New to the Coffee Express train?
  That's okay.  You can sign up here.
</p>

<%= render 'form' %>

<div>
<%= link_to 'Our passengers', passengers_path %>
</div>

<div>
<a href="/" title="home">↩ Back to the station</a>
</div>

app/views/passengers/show.html.erb
<h1><%= @passenger.name %></h1>

<p>
  The <%= @passenger.name %>
  has been know to say
  &ldquo;<%= @passenger.saying %>&rdquo;
</p>

<p>
  Not what you expected?
  <%= link_to 'Update', edit_passenger_path(@passenger) %>
</p>

<div>
  <a href="/passengers">See All Passengers</a>
</div>

<div>
<a href="/" title="home">↩ Back to the station</a>
</div>

app/views/welcome/index.html.erb
<h2>What's that I hear in the distance?</h2>

<pre>
                                               ______
                                          .-"""".._'.       _,##
                                   _..__ |.-"""-.|  |   _,##'`-._
                                  (_____)||_____||  |_,##'`-._,##'`
                                  _|   |.;-""-.  |  |#'`-._,##'`
                               _.;_ `--' `\    \ |.'`\._,##'`
                              /.-.\ `\     |.-";.`_, |##'`
                              |\__/   | _..;__  |'-' /
                              '.____.'_.-`)\--' /'-'`
                               //||\\(_.-'_,'-'`
                             (`-...-')_,##'`
                          _,##`-..,-;##`
                       _,##'`-._,##'`
                    _,##'`-._,##'`
                      `-._,##'`


</pre>

<h1>Why it's the Coffee Express train!</h1>

<div>
  <i>chugga chugga chugga...</i>
</div>

<section>
  <h1>Station Directory</h1>

  <ul>
    <li><%= link_to 'Our passengers', controller: 'passengers' %></li>
    <li><%= link_to 'New passenger singup', new_passenger_path %></li>
  </ul>

</section>

<section>
  <h1>New to the Coffee Express line?</h1>

  <p>
    That's okay.
    <%= link_to 'New passengers are always welcome.', new_passenger_path %>
  </p>
</section>